app="nifi-fly"
primary_region="iad" # Region: Virginia

[mounts]
  source="nifi_data"
  destination="/opt/nifi/nifi-current"
 
[[services]]
  internal_port=8080
  protocol="tcp"
  [[services.ports]]
    handles=["http"]
    port=80
  [[services.ports]]
    handles=["tls","http"]
    port=443
