app="nifi-fly"
primary_region="gru" # Region: Mais proximas do Brasil

[build]
  dockefile="Dockerfile"

[env]
  NIFI_WEB_HTTP_PORT="8080"
  NIFI_WEB_HTTP_HOST="0.0.0.0"

[[services]]
  internal_port=8080
  protocol="tcp"
  [[services.ports]]
    handles=["http"]
    port=80
  [[services.ports]]
    handles=["tls","http"]
    port=443
  [[services.tcp_checks]]
    interval="30s"
    timeout="5s"
    grace_period="30s"
